version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./packages:/usr/share/nginx/html  # Use a bind mount instead of a volume
    restart: always

